name: Rust

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --verbose
      - name: Tests
        run: cargo test --verbose
      - name: Test1
        run: if [ "$(echo -e "1\n2\n3\n1\n124515\n-1" | cargo run)" = 124522 ]; then echo "TEST 1 PASSED"; else echo "TEST 1 FAILED"; exit 105; fi
      - name: Test2
        run: if [ "$(echo -e "7\n9\n45\n321\n2\n3\n1\n124515\n1\n6\n7\n5\n7\n1\n9\n2\n120\n3\n6\n9\n0\n4\n-1" | cargo run)" = 125083 ]; then echo "TEST 2 PASSED"; else echo "TEST 2 FAILED"; exit 105; fi
      - name: Test3
        run: if [ "$(echo -e "1\n-1" | cargo run)" = 1 ]; then echo "TEST 3 PASSED"; else echo "TEST 3 FAILED"; exit 105; fi
      - name: Test4
        run: if [ "$(echo -e "7\n9\n45\n321\n2\n3\n1\n124515\n1\n6\n7\n5b\n7\n1\n9\n2\n120\n3\n6\n9\n0\n4\n-1" | cargo run)" = NaN ]; then echo "TEST 4 PASSED"; else echo "TEST 4 FAILED"; exit 105; fi
      - name: Test5
        run: if [ "$(echo -e "7\n9\n45\n321\n2\n3\n1\n124515\n1\n6\n7\n5\n7\n1\n9\n2\n120\n3\n6\n9\n0\n4\n-1\n4\-1\-3\-6" | cargo run)" = 125083 ]; then echo "TEST 5 PASSED"; else echo "TEST 5 FAILED"; exit 105; fi
      - name: Test6
        run: if [ "$(echo -e "-1" | cargo run)" = 0 ]; then echo "TEST 6 PASSED"; else echo "TEST 6 FAILED"; exit 105; fi